sudo: required
before_install:
  - sudo apt-get -qq update 
  - sudo apt-get install -y cmake libgtest-dev
language: cpp
before_script:
  - cd /usr/src/gtest 
  - sudo cmake CMakeLists.txt && sudo make
  - sudo cp *.a /usr/lib
script: 
  - mkdir $TRAVIS_BUILD_DIR/test/build && cd $TRAVIS_BUILD_DIR/test/build 
  - cmake .. && make 
  - ./runTests
